"""add_notification_sent_to_post

Revision ID: dd498f65c37e
Revises: 5026f14c1c10
Create Date: 2026-06-15 16:52:22.539982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd498f65c37e'
down_revision: Union[str, Sequence[str], None] = '5026f14c1c10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('notification_sent', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'notification_sent')
    # ### end Alembic commands ###
